version: "3"
services:
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret@123"
    ports:
      - 3306:3306
    volumes:
      - /mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 9090:9090
    volumes:
      - ./:/run/
    restart: unless-stopped
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
