version: "3"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=passwd@123
      - MYSQL_DATABASE=internship
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql


  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASS=passwd@123
      - MYSQL_PORT=3306
    depends_on:
      - db
    ports:
      - 9090:9090
    volumes:
      - ./:/app/

volumes:
  mysql_data:
