version: "3"
services:
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - /mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PASS}
    ports:
      - 9090:9090
    volumes:
      - ./:/run/
    restart: unless-stopped
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
