pipeline {
    agent any

    stages {
        stage('CI') {
            steps {
                git 'https://github.com/'
                withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
                docker login -u ${USERNAME} -p ${PASSWORD}
                docker build . -t mohamed7khalifa/ --network host
                docker push mohamed7khalifa/
                """
                }
            }
        }
         stage('CD') {
            steps {
                git 'https://github.com/'
                withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
                kubectl apply -f /var/jenkins_home/workspace/lexalyzer/app/app.yaml
                kubectl apply -f /var/jenkins_home/workspace/lexalyzer/app/service-app.yaml
                """
                }
            }
        }
    }
}