apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-app.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "api-app.labels" . | nindent 4 }}
data:
  MYSQL_USER: "root"
  MYSQL_PASS: "secret@123"
  MYSQL_HOST: "10.244.0.6"
  MYSQL_PORT: "3306"