apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret@123
      #     volumeMounts:
      #       - name: database-persistent-storage
      #         mountPath: /var/lib/mysql
      # volumes:
      #   - name: database-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: database-pvc
