apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: database
